const LOGIN = 'LOGIN';
const QUIT = 'QUIT';
const LOADER_ON = 'LOADER_ON';
const LOADER_OFF = 'LOADER_OFF';
const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export {
  LOGIN, QUIT, LOADER_ON, LOADER_OFF, REGISTRATION_SUCCESS,
};
