const LOGIN = 'LOGIN';
const QUIT = 'QUIT';
const LOADER_ON = 'LOADER_ON';
const LOADER_OFF = 'LOADER_OFF';
const BURGER_ACTIVATED = 'BURGER_ACTIVATED';
const BURGER_INACTIVATED = 'BURGER_INACTIVATED';

export {
  LOGIN, QUIT, LOADER_ON, LOADER_OFF, BURGER_ACTIVATED, BURGER_INACTIVATED,
};
