const LOGIN = 'LOGIN';
const QUIT = 'QUIT';
const LOADER_ON = 'LOADER_ON';
const LOADER_OFF = 'LOADER_OFF';
const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const BURGER_ACTIVATED = 'BURGER_ACTIVATED';
const BURGER_INACTIVATED = 'BURGER_INACTIVATED';
const LOGIN_TRUE = 'true';
const LOGIN_FALSE = 'false';

export {
  LOGIN,
  QUIT,
  LOADER_ON,
  LOADER_OFF,
  BURGER_ACTIVATED,
  BURGER_INACTIVATED,
  REGISTRATION_SUCCESS,
  LOGIN_TRUE,
  LOGIN_FALSE,
};
